apiVersion : apps/v1
kind: Deployment
metadata:
  name: "dominikkluster-3482"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "dominikkluster-3482"
  template:
    metadata:
      labels:
        app: "dominikkluster-3482"
    spec:
      containers:
        - name: "dominikkluster-3482"
          image: "dominikregistryacr.azurecr.io/dominikkluster"
          ports:
          - containerPort: 80