apiVersion: v1
kind: Service
metadata:
    name: "dominikcluster-7b06"
    labels:
        app: "dominikcluster-7b06"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "dominikcluster-7b06"