on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: dominikrefsrt213132.azurecr.io
        username: ${{ secrets.acr_dominikrefsrt213132_username }}
        password: ${{ secrets.acr_dominikrefsrt213132_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t dominikrefsrt213132.azurecr.io/kubedominikklust:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push dominikrefsrt213132.azurecr.io/kubedominikklust:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kubedominikklust_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kubedominikklust9abc | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kubedominikklust9abc`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kubedominikklust9abc
        container-registry-url: dominikrefsrt213132.azurecr.io
        container-registry-username: ${{ secrets.acr_dominikrefsrt213132_username }}
        container-registry-password: ${{ secrets.acr_dominikrefsrt213132_password }}
        secret-name: kubedominikkdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kubedominikklust9abc
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          dominikrefsrt213132.azurecr.io/kubedominikklust:${{ github.sha }}
        imagepullsecrets: |
          kubedominikkdockerauth
