on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: dominikregistryacr.azurecr.io
        username: ${{ secrets.acr_dominikregistryacr_username }}
        password: ${{ secrets.acr_dominikregistryacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t dominikregistryacr.azurecr.io/dominikkluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push dominikregistryacr.azurecr.io/dominikkluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_dominikkluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep dominikkluster8abb | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace dominikkluster8abb`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: dominikkluster8abb
        container-registry-url: dominikregistryacr.azurecr.io
        container-registry-username: ${{ secrets.acr_dominikregistryacr_username }}
        container-registry-password: ${{ secrets.acr_dominikregistryacr_password }}
        secret-name: dominikklustdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: dominikkluster8abb
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          dominikregistryacr.azurecr.io/dominikkluster:${{ github.sha }}
        imagepullsecrets: |
          dominikklustdockerauth
